### ISSUE TITLE
Criar estrutura inicial do projeto

### ISSUE THREAD

**Issue by igorshiohara** [materasystems/crud-microservices#1]
Este ticket está incluído apenas criar a estrutura inicial de módulos do projeto, ou seja, criar os módulos de core, middle, client e edge.

> pom.xml (principal)
  -> pom.xml (core)
  -> pom.xml (middle)
  -> pom.xml (edge)
  -> pom.xml (client)

Não é necessário adicionar nenhuma dependência neste ticket.

**Comment by rochapaulo** [comment]
Done
