### ISSUE TITLE
[5 hrs] Middle - Criar buscas byId, byName, findAll

### ISSUE THREAD

**Issue by igorshiohara** [materasystems/crud-microservices#10]
Uma pessoa específica:
@GET (@PathParam String id)
/crudmicroservices/person/{id}

Todas pessoas:
@GET
/crudmicroservices/person/all

Por nome (@QueryParam String name):
@GET
/crudmicroservices/person?name=XXX

Criar a camada de serviço, que chama a camada de repositório.
Adiciona Cache nesses métodos

**Comment by rochapaulo** [comment]
QueryParam should be used when the argument is optional, when querying by name that argument is mandatory, so I`ll implement using PathParam, ok?

**Comment by Falci** [comment]
I guess the same endpoint should be used to list all, and optionally filter by name or phone number.
At least, this behavior should be applied to edge layer.

**Comment by rochapaulo** [comment]
ok, so I'll implement as @Falci said, the method all will use name and phoneNumber as queryParam. @igorshiohara any problem?

**Comment by igorshiohara** [comment]
Ok, no problem
