### ISSUE TITLE
[8 hrs] Adicionar as dependencias necessárias ao projeto e implementar a infra inicial

### ISSUE THREAD

**Issue by igorshiohara** [materasystems/crud-microservices#2]
- Adicionar as dependências no pom, seguindo as tecnologias que estamos prevendo utilizar.
- Adicionar também os plugins do maven necessário

- Criar as classes de Bootstrap, Modules
- Criar as properties necessárias para o karyon, eureka, archaius

PS: Usar as ultimas versões compatíveis

**Comment by rochapaulo** [comment]
loads of dependencies has already been added to the project on issue #31, this ticket is too generic. As we can add the necessary libs on demand, shall we close that ticket, right?

**Comment by igorshiohara** [comment]
Ok, it can be

**Comment by rochapaulo** [comment]
as suggested, ticket closed
