### ISSUE TITLE
[8 hrs] Implementar a classe de repositorio (store) da classe Person

### ISSUE THREAD

**Issue by igorshiohara** [materasystems/crud-microservices#6]
Essa classe deve conter: save, update, delete, findById, find(byName), findAll

Detalhes de implementação: utilizar Observable, Hystrix, Archaius para carregar as properties do Cassandra que devem ser externalizadas em arquivo.
Documentar cada método

**Comment by rochapaulo** [comment]
#34

**Comment by rochapaulo** [comment]
Done
